// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugncxyhsaybkhhvononr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVnbmN4eWhzYXlia2hodm9ub25yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzkxMTQsImV4cCI6MjA2NTc1NTExNH0.RA_-7PmRD5HEeqjwOL1p8j0iz11VjqszW6dO5LM00N4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);